### ISSUE TITLE
copy column icon toolbar issue

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#132]
When we Select a column and click on Copy icon (in toolbar). It will not display top right toolbar for copied column.

**Comment by navewi** [comment]
I have the same Problem. 
Plus if I copy a column and drag and drop its content in to any other column it remains in the copy. After saving the content ist normal again.

**Comment by NorthstarTech** [comment]
@artf any update on this?

**Comment by JoshLucio** [comment]
Having the same issue, but the toolbar does display, just in the wrong location. It displays in the top left of the page. Dragging it to the same location will also cause it to duplicate again but with the same ID. Editing the content in one of the duplicates will edit the content in both elements because they both have the same ID. Saving and reloading does fix the problem.

**Comment by artf** [comment]
This should be fixed in the latest release.
