### ISSUE TITLE
font color doesn't change - style manager issues

### ISSUE THREAD

**Issue by AliErdin** [artf/grapesjs-mjml#135]
I can't change the font color via style manager / typography / font color

**Comment by izaa** [comment]
Hi, @AliErdin 

just noticed same kind of issue. When changing font size or color, the new size or color is only available if i duplicate the column. 

Something got just broken ..

**Comment by navewi** [comment]
Yeah same with line-height, align, padding, height/width and other style manager settings. Theres some big bug atm.

**Comment by navewi** [comment]
@AliErdin @izaa 
I think I figured out a quick fix. I assume the problem is in the included grape.min,js file. I downloaded the older version of grapes.min.js from this url: https://unpkg.com/grapesjs@0.15.5/dist/grapes.min.js
I pasted the code in an js file in the dist-Folder and included it in the index.php. And deleted the <script src="https://unpkg.com/grapesjs"></script>. Now the style manager is working for me again right now. Feel free to ask if something is unclear for this temporary fix.

**Comment by Clint-Chester** [comment]
There's been a change in [grapesjs 0.15.8](https://github.com/artf/grapesjs/releases/tag/v0.15.8) that now defaults the `config.avoidInlineStyle` to being true. Now if you set this back to being false, all the settings start working again. For example:
```
var editor = grapesjs.init({
    fromElement: true,
    container : '#gjs',
    avoidInlineStyle : false,
    plugins: ['grapesjs-mjml'],
    pluginsOpts: {
      'grapesjs-mjml': {/* ...options */}
    }
});
```
There is a longer term question in play though that the release notes state the support for this configuration will be dropped. @artf it seems that this configuration is required for the grapesjs-mjml plugin so what needs to be done to ensure future compatibility?

**Comment by artf** [comment]
Thanks @Clint-Chester for pointing out the reason. Actually is true, I'd like to remove that option because from web point-of-view is useless but in this case, not having a well-defined API for a custom renderer this option is still crucial (indeed I'll force it in the next release, it doesn't work without). Now I'll keep it in mind before removing that option completely from the code.

ps. online demo updated with the option for now.

**Comment by artf** [comment]
https://github.com/artf/grapesjs-mjml/releases/tag/v0.1.15

**Comment by kickbk** [comment]
I believe the avoidInlineStyles solution is only partial.
Do this:
paste this MJML to import into the canvas:
<mjml>
```
<mj-body>
  <mj-section>
    <mj-column>
      <mj-button>
        <span style="color:#e74c3c;">Button</span>
      </mj-button>
    </mj-column>
  </mj-section>
</mj-body>
```

Great - it works. Now click the View Code button to export. You will notice that the span around the text that had the color style is gone and an id was entered instead.

This is a major problem as we use the export function to produce the MJML, and save MJML templates. Any solutions? Maybe a fix for the import/export?

**Comment by Clint-Chester** [comment]
I'd look at opening it up as a separate issue @kickbk as like you said it's dropping it on the import, where as the issue you commented on here was around settings not sticking when using the Style Manager.

**Comment by kickbk** [comment]
@Clint-Chester sorry, thought it was somehow related. Created https://github.com/artf/grapesjs-mjml/issues/147

**Comment by KashafS98** [comment]
> avoidInlineStyle : false,

:+1:
