### ISSUE TITLE
Canvas does not render when pulled in to angular

### ISSUE THREAD

**Issue by chezhiane** [artf/grapesjs-mjml#159]
Hi , installed this package ( npm i grapesjs-mjml) 
The editor renders good but unable to drag any component in to the canvas.

Am i missing something here . Please correct me.

appcomponet.ts:
import { Component, OnInit } from '@angular/core';
import grapesjs from 'grapesjs';
import grapesJSMJML from 'grapesjs-mjml'

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  private editor: any;
  

  constructor() {
    grapesjs.plugins.add('grapesjs-mjml', grapesJSMJML );

  }
  

  ngOnInit() {
    this.editor = grapesjs.init({
      container: "#gjs",
      plugins: [ "grapesjs-mjml" ]}
     );
  }

  }

Note - Uncaught TypeError: ct[it].model.isComponent is not a function

**Comment by mval1002** [comment]
I've found you need to provide some amount of starting template. Columns can only be added to the `<mj-body>` element (and the other components can only be added to columns), so the editor needs to be initialized with that. This is what I use as the `components` property of the `init` function options:
```
<mjml >
	<mj-body>
		<mj-section padding="0">
			<mj-column>
				<mj-text>Start Here</mj-text>
			</mj-column>
		</mj-section>
	</mj-body>
</mjml>
```

The section+column is important as well, otherwise the body will have 0 height, and it would still be impossible to drag anything into it.
